name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libarmadillo-dev \
            libboost-iostreams-dev \
            libboost-program-options-dev \
            liblapack-dev \
            libblas-dev \
            zlib1g-dev

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build caper and power
        run: cmake --build build --config Release --target caper power
